import { Event } from '../types/event';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Endurance Cup',
    description: 'Endurance racing event at Autodrom Most.',
    date: '2026-03-08',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-endurance-cup-p20084/',
    category: 'sports',
  },
  {
    id: '2',
    title: 'Běh ULTRA MOST 2026',
    description: 'Ultra endurance racing event spanning multiple days.',
    date: '2026-03-26',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-beh-ultra-most-2026-p20143/',
    category: 'sports',
  },
  {
    id: '3',
    title: 'Edda Cup',
    description: 'Racing competition at the circuit.',
    date: '2026-03-28',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-edda-cup-p20174/',
    category: 'sports',
  },
  {
    id: '4',
    title: 'BMW M Day',
    description: 'BMW M series racing and showcase event.',
    date: '2026-03-29',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/bmw-m-day-p20176/',
    category: 'sports',
  },
  {
    id: '5',
    title: 'Deutsche Rundstreckenmeisterschaft',
    description: 'German circuit racing championship.',
    date: '2026-03-30',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-deutsche-rundstreckenmeisterschaft-p20088/',
    category: 'sports',
  },
  {
    id: '6',
    title: 'Carbonia Cup',
    description: 'Racing cup competition at the circuit.',
    date: '2026-04-12',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-carbonia-cup-p20085/',
    category: 'sports',
  },
  {
    id: '7',
    title: 'Porsche Day',
    description: 'Porsche racing and enthusiast event.',
    date: '2026-04-19',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/porsche-day-p20175/',
    category: 'sports',
  },
  {
    id: '8',
    title: 'Histo Cup',
    description: 'Historic racing vehicles competition.',
    date: '2026-04-24',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-histo-cup-p20086/',
    category: 'sports',
  },
  {
    id: '9',
    title: 'Regio CUP',
    description: 'Regional racing cup event.',
    date: '2026-05-01',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-regio-cup-p20177/',
    category: 'sports',
  },
  {
    id: '10',
    title: 'CR Moto Sprint & Endurance',
    description: 'Czech Republic motorcycle sprint and endurance championship.',
    date: '2026-05-08',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-cr-moto-sprint-endurance-p20188/',
    category: 'sports',
  },
  {
    id: '11',
    title: 'WorldSBK Czech Round 2026',
    description: 'World Superbike Championship Czech Round - premier motorcycle racing event.',
    date: '2026-05-14',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/superbike/',
    category: 'sports',
  },
  {
    id: '12',
    title: 'VFV GLP (pravidelnosti)',
    description: 'Regularity racing event.',
    date: '2026-05-29',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-vfv-glp-zavody-pravidelnosti-automobilu-a-motocyklu-p20178/',
    category: 'sports',
  },
  {
    id: '13',
    title: 'German Moto Masters',
    description: 'German motorcycle racing masters championship.',
    date: '2026-06-12',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-german-moto-masters-p20179/',
    category: 'sports',
  },
  {
    id: '14',
    title: 'Schleifer Sprintrennen',
    description: 'Sprint racing competition.',
    date: '2026-06-19',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-schleifer-sprintrennen-p20190/',
    category: 'sports',
  },
  {
    id: '15',
    title: 'Euro Moto',
    description: 'European motorcycle racing event.',
    date: '2026-06-26',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-euro-moto-p20180/',
    category: 'sports',
  },
  {
    id: '16',
    title: 'Minimotoracing ČR',
    description: 'Czech minimotor racing championship at the polygon.',
    date: '2026-07-03',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-minimotoracing-cr-p20562/',
    category: 'sports',
  },
  {
    id: '17',
    title: 'Carbonia Cup',
    description: 'Racing cup competition at the circuit.',
    date: '2026-07-09',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-carbonia-cup-p20328/',
    category: 'sports',
  },
  {
    id: '18',
    title: 'International Sidecar Trophy',
    description: 'International sidecar motorcycle racing trophy.',
    date: '2026-07-10',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-international-sidecar-trophy-p20192/',
    category: 'sports',
  },
  {
    id: '19',
    title: 'WSB Sport Cup',
    description: 'World Superbike sport cup racing event.',
    date: '2026-07-10',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-wsb-sport-cup-p20191/',
    category: 'sports',
  },
  {
    id: '20',
    title: 'Action Bike Race Weekend',
    description: 'Motorcycle racing weekend with multiple events.',
    date: '2026-07-17',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-action-bike-race-weekend-p20193/',
    category: 'sports',
  },
  {
    id: '21',
    title: 'Formula Student',
    description: 'Student engineering competition featuring formula-style racing cars.',
    date: '2026-07-17',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-formula-student-p20181/',
    category: 'sports',
  },
  {
    id: '22',
    title: 'FIA European Zone & GT Cup',
    description: 'FIA European Zone GT racing cup championship.',
    date: '2026-07-31',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-fia-european-zone-gt-cup-series-p20182/',
    category: 'sports',
  },
  {
    id: '23',
    title: 'Motomonster Sprint & Endurance',
    description: 'Motorcycle sprint and endurance racing event.',
    date: '2026-08-21',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-motomonster-sprint-endurance-p20194/',
    category: 'sports',
  },
  {
    id: '24',
    title: 'CZECH TRUCK & NASCAR PRIX 2026',
    description: 'Major truck racing and NASCAR event - one of the biggest racing events of the year.',
    date: '2026-08-27',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-czech-truck-nascar-prix-2026-p20022/',
    category: 'sports',
  },
  {
    id: '25',
    title: 'Le Most',
    description: 'Endurance racing event inspired by Le Mans.',
    date: '2026-09-03',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-le-most-p20087/',
    category: 'sports',
  },
  {
    id: '26',
    title: 'CR Moto Sprint & Endurance',
    description: 'Czech Republic motorcycle sprint and endurance championship.',
    date: '2026-09-11',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-cr-moto-sprint-endurance-p20195/',
    category: 'sports',
  },
  {
    id: '27',
    title: 'Rehm Race Days',
    description: 'Multi-day racing event at the circuit.',
    date: '2026-09-18',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-rehm-race-days-p20196/',
    category: 'sports',
  },
  {
    id: '28',
    title: 'Rennevents Sprint & Endurance',
    description: 'Sprint and endurance racing competition.',
    date: '2026-09-25',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-rennevents-sprint-endurance-p20197/',
    category: 'sports',
  },
  {
    id: '29',
    title: 'Trackmasters (Time Attack Cup)',
    description: 'Time attack racing competition for track enthusiasts.',
    date: '2026-10-09',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-trackmasters-time-attack-cup-p20183/',
    category: 'sports',
  },
  {
    id: '30',
    title: 'THE MOST CLASSIC',
    description: 'Classic automobile festival celebrating vintage and classic racing vehicles.',
    date: '2026-10-10',
    location: 'Autodrom Most, Czech Republic',
    url: 'https://www.autodrom-most.cz/nazev-zavodu-the-most-classic-automobilovy-festival-p20184/',
    category: 'sports',
  },
  {
    id: '31',
    title: 'Regional Championship West (CCVD)',
    description: 'Cheerleading championships in Rhineland-Palatinate and western Germany.',
    date: '2026-01-24',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/cheerleading',
    category: 'other',
  },
  {
    id: '32',
    title: 'SC Regionals & STAGE Events West',
    description: 'Cheerleading action at the ring°arena.',
    date: '2026-01-25',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/cheerleading',
    category: 'other',
  },
  {
    id: '33',
    title: 'ADAC RAVENOL NÜRBURGRING LANGSTRECKEN-SERIE',
    description: 'Racing on the Nordschleife multiple times yearly.',
    date: '2026-03-14',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/nls',
    category: 'sports',
  },
  {
    id: '34',
    title: 'GLP REGULARITY TEST',
    description: 'Drive with consistent lap times; smallest deviation wins.',
    date: '2026-03-21',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/glp',
    category: 'sports',
  },
  {
    id: '35',
    title: 'RCN CIRCUIT CHALLENGE',
    description: 'Gateway to motorsport on demanding race track.',
    date: '2026-03-21',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/rcn',
    category: 'sports',
  },
  {
    id: '36',
    title: 'DARTS AT THE RING GALA',
    description: 'Top-class darts, electric atmosphere, and supporting program.',
    date: '2026-03-28',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/darts',
    category: 'other',
  },
  {
    id: '37',
    title: 'ADAC 24h NÜRBURGRING QUALIFIERS',
    description: '11 hours racing; dress rehearsal for main event.',
    date: '2026-04-17',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/quali-24h',
    category: 'sports',
  },
  {
    id: '38',
    title: 'NÜRBURGRING DRIFT CUP',
    description: 'Europe\'s best drifters compete in door-to-door duels.',
    date: '2026-04-25',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/drift-cup',
    category: 'sports',
  },
  {
    id: '39',
    title: 'MOTORCYCLISTS\' MASS \'REV UP\'',
    description: 'Season kickoff; approximately 42,000 bikers.',
    date: '2026-04-26',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/motorcycle/anlassen',
    category: 'sports',
  },
  {
    id: '40',
    title: 'ADAC RAVENOL 24H NÜRBURGRING',
    description: '140 race cars competing around world\'s longest track.',
    date: '2026-05-14',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/24h-race',
    category: 'sports',
  },
  {
    id: '41',
    title: 'DMV GOODYEAR RACING DAYS',
    description: 'Ten thrilling race series debut at Nürburgring.',
    date: '2026-05-29',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/dmv',
    category: 'sports',
  },
  {
    id: '42',
    title: 'ROCK AM RING',
    description: 'SOLD OUT - Music festival at legendary venue.',
    date: '2026-06-05',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/rock-am-ring',
    category: 'concert',
  },
  {
    id: '43',
    title: 'ADAC NÜRBURGRING CLASSIC',
    description: 'Authentic successor to 1927 inaugural race.',
    date: '2026-06-12',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/oldtimer/nuerburgring-classic',
    category: 'sports',
  },
  {
    id: '44',
    title: 'MICHELIN 12H NÜRBURGRING',
    description: 'First Michelin 24H Series stop at venue.',
    date: '2026-07-03',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/12hoursnuerburgring',
    category: 'sports',
  },
  {
    id: '45',
    title: 'DLMM AT THE RING',
    description: 'Europe\'s largest e-darts tournament.',
    date: '2026-07-03',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/dlmm',
    category: 'other',
  },
  {
    id: '46',
    title: 'INT. ADAC TRUCK-GRAND-PRIX',
    description: 'Motorsport, music festival, trade fair.',
    date: '2026-07-10',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/adac-truck-grand-prix',
    category: 'sports',
  },
  {
    id: '47',
    title: 'RAD AM RING',
    description: 'Record 11,948 participants in 2025.',
    date: '2026-07-24',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/rad-am-ring',
    category: 'other',
  },
  {
    id: '48',
    title: 'BELMOT OLDTIMER-GRAND-PRIX',
    description: '53rd historic Nürburgring August event.',
    date: '2026-08-07',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/oldtimer/oldtimer-grand-prix',
    category: 'sports',
  },
  {
    id: '49',
    title: 'DTM',
    description: 'Thrilling racing with lead changes.',
    date: '2026-08-14',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/dtm',
    category: 'sports',
  },
  {
    id: '50',
    title: 'KÖLNER KURS',
    description: 'Historic racing machines on Grand Prix track.',
    date: '2026-08-22',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/motorcycle/koelner-kurs',
    category: 'sports',
  },
  {
    id: '51',
    title: 'GT WORLD CHALLENGE EUROPE',
    description: 'World\'s largest GT series three-hour race.',
    date: '2026-08-28',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/gt-world-challenge',
    category: 'sports',
  },
  {
    id: '52',
    title: 'EURO MOTO',
    description: 'New season following dramatic 2025.',
    date: '2026-09-04',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/motorcycle/idm',
    category: 'sports',
  },
  {
    id: '53',
    title: 'ADAC 1000km RACE',
    description: 'Legendary long-distance race since 1953.',
    date: '2026-09-19',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/oldtimer/1000-kilometer-race',
    category: 'sports',
  },
  {
    id: '54',
    title: 'ADAC RGB SEASON FINALE',
    description: 'Dozen racing series in one weekend.',
    date: '2026-10-02',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/oldtimer/rgb-season-finale',
    category: 'sports',
  },
  {
    id: '55',
    title: 'ADAC WESTFALEN TROPHY',
    description: 'Historic cars meet modern touring cars.',
    date: '2026-10-16',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/automotive/westfalen-trophy',
    category: 'sports',
  },
  {
    id: '56',
    title: 'NÜRBURGRING FAMILY DAY',
    description: '20,000 visitors; activities for families.',
    date: '2026-10-25',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/family-day',
    category: 'other',
  },
  {
    id: '57',
    title: 'BÜLENT CEYLAN - DIKTATÜRK',
    description: 'Comedy program at Bitburger Event Center.',
    date: '2027-06-12',
    location: 'Nürburgring, Germany',
    url: 'https://nuerburgring.de/events/categories/entertainment/buelent-ceylan',
    category: 'other',
  },
];
